/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prueba de vida + conectividad a la base de datos */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea usuario + NeatProfile + NeatWallet (atómico) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NeatProfile público (currículum vivo) */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edita descripción, habilidades declaradas y cobertura del propio perfil */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Árbol de categorías */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed en vivo (geolocalización enmascarada)
         * @description Expone sólo geo aproximada (radio/zona). La dirección exacta NO se entrega
         *     aquí — se revela sólo con Acuerdo aceptado o urgente asignado (doc 01 §3.3).
         */
        get: operations["listOpportunities"];
        put?: never;
        /** Publica una oportunidad (urgente o programada) */
        post: operations["createOpportunity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de oportunidad */
        get: operations["getOpportunity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El cliente revisa las postulaciones */
        get: operations["listApplications"];
        put?: never;
        /** Postular a una oportunidad programada */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top profesionales sugeridos + explicación (reason codes)
         * @description RBAC obligatorio; rate-limited. No expone el Trust Score crudo con flag
         *     EMERGING a no-clientes (anti-IDOR, doc 02 §10).
         */
        get: operations["getMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{id}/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre la Sala de Acuerdo (estado ABIERTA) */
        post: operations["openAgreement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado, versión vigente, partes y Trust Scores */
        get: operations["getAgreement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propone una nueva versión de términos (→ PROPUESTA) */
        post: operations["proposeVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/price-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contraoferta con justificación (Precio Justo)
         * @description 422 si falta `justificacion` (doc 03 §11).
         */
        post: operations["makePriceOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/price-offers/{oid}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acepta una contraoferta (su monto se escribe en una nueva versión) */
        post: operations["acceptPriceOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acepta la versión vigente por tu parte (requiere step-up de identidad)
         * @description Exige confirmación de step-up (PIN/biometría), obligatoria sobre umbral de monto
         *     para no repudio. Con versión desactualizada → 409. La doble aceptación gatilla la
         *     retención de escrow; si la retención falla, el acuerdo pasa a PAGO_FALLIDO (doc 03).
         */
        post: operations["acceptAgreement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/amendments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enmienda de alcance durante EN_EJECUCION
         * @description Sólo válida en EN_EJECUCION; sobre umbral % exige evidencia/alerta NeatAI (doc 03 §11).
         */
        post: operations["amend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** El profesional marca "trabajo entregado" (→ ENTREGADO, abre ventana de reclamo) */
        post: operations["deliver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * El cliente confirma la entrega (→ CERRADO + libera escrow)
         * @description Si vence la ventana de reclamo (24–48h), la liberación es automática (doc 03 §10).
         */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela el acuerdo según política de estado */
        post: operations["cancelAgreement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mensajes de la sala */
        get: operations["listMessages"];
        put?: never;
        /** Envía un mensaje (NeatAI puede advertir sobre contacto externo) */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia la ejecución del servicio */
        post: operations["startService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finaliza la ejecución (abre ventana de disputa) */
        post: operations["finishService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre una disputa (congela el escrow → EN_DISPUTA) */
        post: operations["openDispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saldo (derivado) + movimientos paginados
         * @description El saldo es una proyección `Σ créditos − Σ débitos`; gana el ledger (doc 04 §1).
         */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia un abono vía MercadoPago
         * @description No asienta; el asiento se crea sólo al recibir `approved` por webhook (doc 04 §6).
         */
        post: operations["topup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retiro a banco (2FA + KYC)
         * @description Billetera → PASARELA → payout MercadoPago. Requiere 2FA; sobre umbral, KYC reforzado (doc 04 §8).
         */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle auditable de una transacción (todos sus asientos)
         * @description Verifica pertenencia antes de responder (anti-IDOR, doc 04 §9).
         */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retención en escrow al ACORDAR (interno, desde la Sala de Acuerdo) */
        post: operations["holdEscrow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Liberación al profesional (comisión 20%)
         * @description 409 si el servicio no está ENTREGADO+confirmado (o ventana vencida). Nunca unilateral (doc 04 §9).
         */
        post: operations["releaseEscrow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reembolso total/parcial (desde Resolución de Conflictos)
         * @description No se cobra comisión sobre un reembolso; en resolución dividida es proporcional (doc 04 §5).
         */
        post: operations["refund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/mercadopago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * FUENTE DE VERDAD del estado de pago
         * @description Verifica firma HMAC `x-signature`, deduplica por event-id (idempotente),
         *     aplica anti-replay y confirma con `GET /payments/{id}` server-side antes de
         *     asentar. Reprocesar el mismo evento no duplica asientos (doc 04 §6).
         */
        post: operations["mercadopagoWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluar (bidireccional, double-blind)
         * @description 409 si el servicio no está pagado (CERRADO = escrow liberado). El cuerpo trae
         *     estrellas + atributos, NUNCA el 0–100 (se deriva server-side). Double-blind:
         *     se publica al enviar ambas partes o vencer la ventana (doc 05 §2, §11).
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{id}/trust-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trust Score derivado
         * @description Sin datos crudos que permitan IDOR para no-clientes (doc 05 §11).
         */
        get: operations["getTrustScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{id}/reputation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial público paginado (derivado del log) */
        get: operations["getReputation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/reputation/recompute/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recomputa la proyección del Trust Score desde el log */
        post: operations["recomputeReputation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example CONFLICT */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            nombre: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResult: {
            token?: string;
            usuario?: components["schemas"]["NeatProfile"];
        };
        /** @description Currículum vivo; unidad de reputación (1—1 con usuario). doc 01 §1.3, doc 05 §10 */
        NeatProfile: {
            id?: string;
            usuario_id?: string;
            nombre?: string;
            descripcion?: string;
            habilidades?: string[];
            /** @description Identidad Verificada (Pilar I) */
            nivel_verificacion?: number;
            trust_score?: components["schemas"]["TrustScoreView"];
            /** @description "Nuevo en NeatSpace" en cold-start */
            badge?: string | null;
        };
        ProfilePatch: {
            descripcion?: string;
            habilidades?: string[];
            cobertura?: components["schemas"]["Cobertura"];
        };
        Cobertura: {
            centro?: components["schemas"]["GeoAprox"];
            radio_km?: number;
        };
        Categoria: {
            id?: string;
            nombre?: string;
            parent_id?: string | null;
            nivel?: number;
            /** @description Requiere verificación reforzada (doc 02 §4.2) */
            sensible?: boolean;
        };
        /** @description Geolocalización aproximada (zona/comuna). Nunca la dirección exacta en el feed. */
        GeoAprox: {
            lat_aprox?: number;
            lng_aprox?: number;
            zona?: string;
            radio_m?: number;
        };
        OportunidadInput: {
            /** @enum {string} */
            tipo: "urgent" | "scheduled";
            categoria: string;
            geo: components["schemas"]["GeoAprox"];
            /** @description CLP */
            precio_ref?: number;
            /** Format: date-time */
            fecha?: string | null;
            descripcion?: string;
        };
        Oportunidad: {
            id?: string;
            /**
             * @description Inmutable (doc 02)
             * @enum {string}
             */
            tipo?: "urgent" | "scheduled";
            categoria?: string;
            /** @enum {string} */
            estado?: "publicado" | "tomada" | "cerrada" | "sin_cobertura";
            geo?: components["schemas"]["GeoAprox"];
            precio_ref?: number;
            /** @description Fallback SinCobertura (doc 02) */
            convertida_desde_id?: string | null;
            /** Format: date-time */
            creado_en?: string;
        };
        /** @description Vista de feed con geo enmascarada; sin dirección exacta. */
        OportunidadFeedItem: {
            id?: string;
            /** @enum {string} */
            tipo?: "urgent" | "scheduled";
            categoria?: string;
            /** @description Distancia agrupada en rangos (doc 02 §6.3) */
            distancia_rango?: string;
            geo?: components["schemas"]["GeoAprox"];
            precio_ref?: number;
        };
        Postulacion: {
            id?: string;
            profesional_id?: string;
            mensaje?: string;
            /** Format: date-time */
            creado_en?: string;
        };
        Match: {
            profesional_id?: string;
            score_ranking?: number;
            reason_codes?: string[];
            badge?: string | null;
        };
        Acuerdo: {
            id?: string;
            oportunidad_id?: string;
            /** @enum {string} */
            estado?: "ABIERTA" | "PROPUESTA" | "PAGO_FALLIDO" | "ACORDADO" | "EN_EJECUCION" | "ENTREGADO" | "EN_DISPUTA" | "CERRADO" | "CANCELADO" | "EXPIRADO";
            version_vigente?: components["schemas"]["AcuerdoVersion"];
            aceptado_cliente?: boolean;
            aceptado_profesional?: boolean;
            /** @description Sólo tras ACORDADO / urgente asignado */
            direccion_revelada?: boolean;
        };
        AcuerdoVersionInput: {
            terminos: components["schemas"]["Terminos"];
        };
        /** @description Snapshot inmutable de términos (doc 03 §4). */
        AcuerdoVersion: {
            n?: number;
            terminos?: components["schemas"]["Terminos"];
            /** Format: date-time */
            creado_en?: string;
        };
        Terminos: {
            /** @description CLP */
            precio?: number;
            duracion?: string;
            materiales?: string | null;
            responsabilidades?: string | null;
            condiciones?: string | null;
        };
        PriceOfferInput: {
            monto: number;
            /** @description Obligatoria (422 si falta). Estilo inDrive. */
            justificacion: string;
        };
        PriceOffer: {
            id?: string;
            monto?: number;
            justificacion?: string;
            /** Format: date-time */
            creado_en?: string;
        };
        AcceptInput: {
            /** @description Versión que se acepta; 409 si ya cambió */
            version_n: number;
            /** @description Confirmación de identidad para no repudio (doc 03 §4.1) */
            step_up: {
                /** @enum {string} */
                metodo?: "pin" | "biometria" | "otro";
                token?: string;
            };
        };
        AmendmentInput: {
            cambio: components["schemas"]["Terminos"];
            evidencia_url?: string | null;
        };
        DisputaInput: {
            motivo: string;
            evidencia_url?: string | null;
        };
        Mensaje: {
            id?: string;
            autor_id?: string;
            texto?: string;
            leido?: boolean;
            /** @description Advertencia de contacto externo (doc 03 §7) */
            alerta_neatai?: string | null;
            /** Format: date-time */
            creado_en?: string;
        };
        MensajeInput: {
            texto: string;
        };
        WalletView: {
            wallet_id?: string;
            /** @description Proyección Σcréditos − Σdébitos (CLP) */
            saldo?: number;
            /** @default CLP */
            moneda: string;
            movimientos?: components["schemas"]["Movimiento"][];
            next_cursor?: string | null;
        };
        Movimiento: {
            transaccion_id?: string;
            /** @enum {string} */
            tipo?: "topup" | "retencion" | "liberacion" | "reembolso" | "reverso" | "retiro";
            monto?: number;
            /** @enum {string} */
            direccion?: "debito" | "credito";
            concepto?: string;
            /** Format: date-time */
            creado_en?: string;
        };
        TopupInput: {
            monto: number;
            /** @description Medio de pago MercadoPago */
            medio?: string;
        };
        WithdrawInput: {
            monto: number;
            /** @description Debe estar a nombre del titular (anti-testaferro) */
            cuenta_bancaria: string;
            twofa_token?: string;
        };
        RefundInput: {
            /** @enum {string} */
            tipo: "total" | "parcial" | "dividido";
            /** @description En resolución dividida */
            monto_profesional?: number | null;
        };
        PagoIntento: {
            pago_id?: string;
            /**
             * @description Confirmación real llega por webhook
             * @enum {string}
             */
            estado?: "pendiente";
        };
        /** @description Agrupador de partida doble; Σ débitos = Σ créditos. doc 04 §3 */
        Transaccion: {
            id?: string;
            /** @enum {string} */
            tipo?: "topup" | "retencion" | "liberacion" | "reembolso" | "reverso" | "retiro";
            referencia_dominio?: string;
            idempotency_key?: string;
            asientos?: components["schemas"]["LedgerEntry"][];
            /** Format: date-time */
            creado_en?: string;
        };
        /** @description Asiento append-only (sin UPDATE/DELETE). doc 04 §3 */
        LedgerEntry: {
            id?: string;
            wallet_id?: string;
            /** @enum {string} */
            direccion?: "debito" | "credito";
            monto?: number;
            concepto?: string;
        };
        MercadoPagoEvent: {
            /** @description event-id único (dedup) */
            id?: string;
            type?: string;
            data?: {
                /** @description payment id → se confirma con GET /payments/{id} */
                id?: string;
            };
            /** @enum {string} */
            status?: "pending" | "in_process" | "approved" | "rejected" | "refunded" | "charged_back";
        };
        ReviewInput: {
            estrellas: number;
            /**
             * @example {
             *       "amable": true,
             *       "rapido": true,
             *       "prolijo": true
             *     }
             */
            atributos?: {
                [key: string]: boolean;
            };
            /** @description Pasa por moderación + limpieza de PII (doc 05 §2) */
            comentario?: string | null;
        };
        /** @description Proyección recomputable; nunca un campo seteable. doc 05 §1, §10 */
        TrustScoreView: {
            valor_0_100?: number;
            /**
             * @example {
             *       "amable": 88,
             *       "rapido": 73
             *     }
             */
            atributos_0_100?: {
                [key: string]: number;
            };
            nivel_verificacion?: number;
            n_evaluaciones?: number;
            badge?: string | null;
        };
        ReputacionEvento: {
            id?: string;
            /** @enum {string} */
            evento?: "evaluacion" | "sancion" | "verificacion" | "apelacion" | "decay";
            resumen?: string;
            /** Format: date-time */
            creado_en?: string;
        };
    };
    responses: {
        /** @description No autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No autorizado (RBAC / pertenencia) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicto de estado (p. ej. versión desactualizada, primero-gana) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Entidad no procesable (validación de negocio) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Límite de tasa excedido */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falta `Idempotency-Key` en una escritura de dinero */
        MissingIdempotencyKey: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathId: string;
        /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio y BD operativos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example up */
                        db?: string;
                    };
                };
            };
            /** @description Degradado (BD no disponible) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Cuenta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Sesión iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil público */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeatProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Perfil actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeatProfile"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: {
                level?: number;
                parent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorías */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
        };
    };
    listOpportunities: {
        parameters: {
            query?: {
                type?: "urgent" | "scheduled";
                /** @description lat,lng */
                near?: string;
                radius?: number;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oportunidades con geo aproximada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OportunidadFeedItem"][];
                };
            };
        };
    };
    createOpportunity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OportunidadInput"];
            };
        };
        responses: {
            /** @description Oportunidad publicada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Oportunidad"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    getOpportunity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oportunidad */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Oportunidad"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listApplications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postulaciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Postulacion"][];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postulación registrada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    getMatches: {
        parameters: {
            query?: {
                /** @description p.ej. speed|price|trust */
                prefs?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking de matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    openAgreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sala abierta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acuerdo"];
                };
            };
        };
    };
    getAgreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acuerdo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acuerdo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    proposeVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcuerdoVersionInput"];
            };
        };
        responses: {
            /** @description Nueva versión propuesta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcuerdoVersion"];
                };
            };
        };
    };
    makePriceOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceOfferInput"];
            };
        };
        responses: {
            /** @description Oferta registrada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceOffer"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    acceptPriceOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
                oid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oferta aceptada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    acceptAgreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInput"];
            };
        };
        responses: {
            /** @description Aceptación registrada (y escrow retenido si ambas partes aceptaron) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Acuerdo"];
                };
            };
            /** @description Versión desactualizada o pago fallido */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    amend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendmentInput"];
            };
        };
        responses: {
            /** @description Enmienda propuesta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    deliver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marcado como entregado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrega confirmada, escrow liberado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelAgreement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelado; escrow resuelto según corresponda */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mensajes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensaje"][];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MensajeInput"];
            };
        };
        responses: {
            /** @description Mensaje enviado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio en ejecución */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finishService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio finalizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openDispute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputaInput"];
            };
        };
        responses: {
            /** @description Disputa abierta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWallet: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Billetera del titular autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletView"];
                };
            };
        };
    };
    topup: {
        parameters: {
            query?: never;
            header: {
                /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopupInput"];
            };
        };
        responses: {
            /** @description Intento de abono iniciado (pendiente) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagoIntento"];
                };
            };
            400: components["responses"]["MissingIdempotencyKey"];
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header: {
                /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawInput"];
            };
        };
        responses: {
            /** @description Retiro en proceso */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaccion"];
                };
            };
            400: components["responses"]["MissingIdempotencyKey"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transacción con sus ledger_entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaccion"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    holdEscrow: {
        parameters: {
            query?: never;
            header: {
                /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fondos retenidos en ESCROW */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaccion"];
                };
            };
            /** @description Retención fallida (→ PAGO_FALLIDO) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    releaseEscrow: {
        parameters: {
            query?: never;
            header: {
                /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Escrow liberado (neto al profesional + comisión) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaccion"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    refund: {
        parameters: {
            query?: never;
            header: {
                /** @description Obligatoria en toda escritura de dinero (400 si falta). doc 04 §9 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundInput"];
            };
        };
        responses: {
            /** @description Reembolso asentado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaccion"];
                };
            };
        };
    };
    mercadopagoWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MercadoPagoEvent"];
            };
        };
        responses: {
            /** @description Evento aceptado/deduplicado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Firma inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Evaluación registrada (oculta hasta publicación simultánea) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Servicio no pagado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTrustScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proyección de reputación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreView"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getReputation: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial de reputación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputacionEvento"][];
                };
            };
        };
    };
    recomputeReputation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proyección recomputada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreView"];
                };
            };
        };
    };
}
